server:
  port: 10001
---
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10000/eureka
  server:
    eviction-interval-timer-in-ms: 30000
    enable-self-preservation: false  #关闭自我保护（缺省为打开）
---
spring:
  application:
    name: eureka-10001